In [1]:
from termcolor import colored
import numpy as np

# Custom error to pass message to
class Dimension_Error(Exception):
    pass

def add_two_matrices(a, b):
    """
        Use to add two matrices that share the same dimensions together.
        Returns C, the sum of the two matrices 

        a,b : Matrices/Tensors to be added together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Addition\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A + B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape != b.shape:
        a_shape = colored(a.shape, 'red', 'on_white', attrs=['bold'] )
        b_shape = colored(b.shape, 'red', 'on_white', attrs=['bold'] )
        error = colored('Error', 'red', attrs=['blink'])
        silly = colored('You trying to break me?', 'blue')
        cust_eror = f"{error} A has shape {a_shape} | B has shape {b_shape}\n{silly}"
        print(cust_eror)
        raise Dimension_Error(cust_eror)
    
    # Add and print results
    c = a + b 
    print(f'C = {c}')
    print('Done :)\n\n')
    return c
          
def subtract_two_matrices(a, b):
    """
        Use to add two matrices that share the same dimensions together.
        Returns C, the difference of the two matrices 

        a,b : Matrices/Tensors to be subtracted together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Subtraction\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A + B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape != b.shape:
        a_shape = colored(a.shape, 'red', 'on_white', attrs=['bold'] )
        b_shape = colored(b.shape, 'red', 'on_white', attrs=['bold'] )
        error = colored('Error', 'red', attrs=['blink'])
        silly = colored('You trying to break me?', 'blue')
        cust_eror = f"{error} A has shape {a_shape} | B has shape {b_shape}\n{silly}"
        print(cust_eror)
        raise Dimension_Error(cust_eror)
    
    # Subtract and print results
    c = a - b 
    print(f'C = {c}')
    print('Done :)\n\n')
    return c
          

def multiply_two_matrices(a, b):
    """
        Use to multiply two matrices that share the same outer and inner dim together.
        Returns C, the product of the two matrices 

        a,b : Matrices/Tensors to be multiplied together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Multiplication\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A x B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape[-1] != b.shape[0]:
        a_shape = colored(a.shape[1], 'red', attrs=['bold', 'underline'] )
        b_shape = colored(b.shape[0], 'red', attrs=['bold', 'underline'] )
        error = colored('Error:', 'red', attrs=['blink'])
        silly = colored('You trying to break me?', 'blue')
        cust_eror = f"{error} (m x {a_shape}) * ({b_shape} x n).. Not compatible\n{silly}"
        print(cust_eror)
        raise Dimension_Error(cust_eror)
    
    # Dot product and print results
    c = np.dot(a, b) 
    print(f'C = {c}')
    print(f'C has shape {c.shape[0]} x {c.shape[1]}')
    print('Done :)\n\n')
    return c

# $$\Large Addition\ of\ Matrices/Tensors\\ $$

$$ \Large A_{m \times n} + B_{m \times n}  =\\ 
\large \begin{matrix}
 a_{11} & a_{12}    & \ldots &  a_{1n}\\
 a_{21}  &   a_{22} & \ldots &  a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 a_{m1}  &    a_{m2}       &\ldots &  a_{mn}
\end{matrix} + \begin{matrix}
 b_{11} & b_{12}    & \ldots &  b_{1n}\\
 b_{21}  &   b_{22} & \ldots &  b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 b_{m1}  &    b_{m2}       &\ldots &  b_{mn}
\end{matrix} = 
\begin{matrix}
 c_{11} & c_{12}    & \ldots &  c_{1n}\\
 c_{21}  &   c_{22} & \ldots &  c_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 c_{m1}  &    c_{m2}       &\ldots &  c_{mn} \end{matrix}  \\
$$

$$
    \Large Where\ A\ and \ B\ are\ both\ m \times n \ matrices
$$

In [2]:
# Two matrices with matching dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (2,3))
c = add_two_matrices(a, b)

Matrix Addition
A = [[19 12 17]
 [ 0 14  0]]

B = [[15 10 13]
 [ 9 19 19]]

A + B = C
A's size = (2, 3)
B's size = (2, 3)

C = [[34 22 30]
 [ 9 33 19]]
Done :)




## Two Matrices with mismatch dimensions... an invalid operation

In [3]:
# Two matrices with mismatch dimension
c = np.random.randint(0, 20, (2,3))
d = np.random.randint(0, 20, (5,2))
add_two_matrices(c, d)

Matrix Addition
A = [[ 1 10  0]
 [ 9  1  7]]

B = [[ 1  3]
 [ 9  1]
 [16 14]
 [17 15]
 [ 3 17]]

A + B = C
A's size = (2, 3)
B's size = (5, 2)

Error A has shape (2, 3) | B has shape (5, 2)
You trying to break me?


Dimension_Error: Error A has shape (2, 3) | B has shape (5, 2)
You trying to break me?

# $$\Large Subtraction\ of\ Matrices/Tensors\\ $$

$$ \Large A_{m \times n} - B_{m \times n}  =\\ 
\large \begin{matrix}
 a_{11} & a_{12}    & \ldots &  a_{1n}\\
 a_{21}  &   a_{22} & \ldots &  a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 a_{m1}  &    a_{m2}       &\ldots &  a_{mn}
\end{matrix} - \begin{matrix}
 b_{11} & b_{12}    & \ldots &  b_{1n}\\
 b_{21}  &   b_{22} & \ldots &  b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 b_{m1}  &    b_{m2}       &\ldots &  b_{mn}
\end{matrix} = 
\begin{matrix}
 c_{11} & c_{12}    & \ldots &  c_{1n}\\
 c_{21}  &   c_{22} & \ldots &  c_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 c_{m1}  &    c_{m2}       &\ldots &  c_{mn} \end{matrix}  \\
$$

$$
    \Large Where\ A\ and \ B\ are\ both\ m \times n \ matrices
$$

In [ ]:
# Two matrices with matching dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (2,3))
c = subtract_two_matrices(a, b)

## Two Matrices with mismatch dimensions... an invalid operation

In [ ]:
# Two matrices with mismatch dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (8,2))
c = subtract_two_matrices(a, b)

# $$\Large Multiplication\ of\ Matrices/Tensors\\ $$

$$ \Large A_{m \times r} \cdot B_{r \times n}  = \\
\large \begin{matrix}
 a_{11} & a_{12}    & \ldots &  a_{1r}\\
 a_{21}  &   a_{22} & \ldots &  a_{2r}\\
\vdots & \vdots & \ddots & \vdots\\
 a_{m1}  &    a_{m2}       &\ldots &  a_{mr}
\end{matrix} \ * \ \begin{matrix}
 b_{11} & b_{12}    & \ldots &  b_{1n}\\
 b_{21}  &   b_{22} & \ldots &  b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 b_{r1}  &    b_{r2}       &\ldots &  b_{rn}
\end{matrix} = 
\begin{matrix}
 c_{11} & c_{12}    & \ldots &  c_{1r}\\
 c_{21}  &   c_{22} & \ldots &  c_{2r}\\
\vdots & \vdots & \ddots & \vdots\\
 c_{r1}  &    c_{r2}       &\ldots &  c_{rr}
\end{matrix} \\
$$

$$
    \Large Where\ A_r\ = \ B_r\ and\ C\ is\ r\times r \ matrix
$$

In [ ]:
# Two matrices with proper dimensions
a = np.random.randint(0, 20, (7,3))
b = np.random.randint(0, 20, (3,20))
c = multiply_two_matrices(a, b)

## Two Matrices with mismatch dimensions... an invalid operation

In [ ]:
# Two matrices with improper dimensions
a = np.random.randint(0, 20, (7,7))
b = np.random.randint(0, 20, (3,20))
c = multiply_two_matrices(a, b)

# $$\large Scalar\ Multiple \ of\ a \ Matrix/Tensor \\
5A = \begin{matrix}
5a_{11} & 5a_{12}    & \ldots & 5a_{1n}\\
5a_{21}  &  5a_{22} & \ldots & 5a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
5a_{m1}  &   5a_{m2}       &\ldots & 5a_{mn}
\end{matrix} \\ $$


In [ ]:
a = np.random.randint(0,10, (2,6))
print(f'Matrix a before scaled\n{"="*48}\n{a}\n')
print(f'Matrix a Scaled by 5\n{"="*48}\n{5 * a}')

# $$ \Large Transpose\ of\ a\ Matrix $$
$$ \Large Simply\ put\ A^\mathsf{T}_{ij} = A_{ji}   $$

<center> <img src="trans.gif">

In [ ]:
a = np.random.randint(0, 20, (3,2, 2))
print(f'Before transpose: \n{"=" * 48}\n {a}')
a = np.transpose(a);
print()
print(f'After transpose: \n{"=" * 48}\n {a}')

# Gauss-Jordan method

In [ ]:
from numpy.linalg import solve

linCombo = np.eye(5)
answer = np.random.rand(5)

print(f'Linear combo:\n {linCombo} *x =  {answer}')
solution = solve(linCombo, np.transpose(answer))
print(f'\nWhere x = {solution.reshape(-1,1) }')
print()


linCombo = np.array([[0,0,1,0], [2,4,1,2], [9,3,1,.8], [22, .128, 4, 9]])
answer = np.array([0, 2, 30, 8])

print(f'Linear combo:\n {linCombo} *x =  {answer}')
solution = solve(linCombo, np.transpose(answer))
print(f'\nWhere x = {solution.reshape(-1,1) }')
print()

# Inverse of a Matrix

In [ ]:
a = np.random.randint(0, 22,(2, 4))
print(f'Before Inverse Operation: \n{"=" * 48}\n {a}')
a = np.invert(a)
print()
print(f'After Inverse Operation: \n{"=" * 48}\n {a}')

# Rank of a Matrix/Tensor

In [ ]:
from numpy.linalg import matrix_rank

# A 4x4 identity array
i = np.eye(4)
print(f'{i}\n Rank: {matrix_rank(i)}')
print()

# Same array but with zeros in the last row
i[-1][:] = np.zeros((1,i.shape[1]))
print(f'{i}\n Rank: {matrix_rank(i)}')


# Determinates of Matrices/Tensors

In [ ]:
from numpy.linalg import det

a = np.random.randint(1, 10, (2, 2))
print(f'{a}\n Determinate: {det(a):.2f}')
print()

norm = np.random.randint(0,14,(5,5))
print(f'{norm}\n Determinate: \n{det(norm):.2f}\n')
print()