In [1]:
from termcolor import colored
import numpy as np

# Custom error to pass message to
class Dimension_Error(Exception):
    pass

def add_two_matrices(a, b):
    """
        Use to add two matrices that share the same dimensions together.
        Returns C, the sum of the two matrices 

        a,b : Matrices/Tensors to be added together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Addition\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A + B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape != b.shape:
        a_shape = colored(a.shape, 'red', 'on_white', attrs=['bold'] )
        b_shape = colored(b.shape, 'red', 'on_white', attrs=['bold'] )
        error = colored('Error', 'red', attrs=['blink'])
        silly = colored('You trying to break me?', 'blue')
        cust_eror = f"{error} A has shape {a_shape} | B has shape {b_shape}\n{silly}"
        print(cust_eror)
        raise Dimension_Error(cust_eror)
    
    # Add and print results
    c = a + b 
    print(f'C = {c}')
    print('Done :)\n\n')
    return c
          
def subtract_two_matrices(a, b):
    """
        Use to add two matrices that share the same dimensions together.
        Returns C, the difference of the two matrices 

        a,b : Matrices/Tensors to be subtracted together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Subtraction\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A + B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape != b.shape:
        a_shape = colored(a.shape, 'red', 'on_white', attrs=['bold'] )
        b_shape = colored(b.shape, 'red', 'on_white', attrs=['bold'] )
        error = colored('Error', 'red', attrs=['blink'])
        silly = colored('You trying to break me?', 'blue')
        cust_eror = f"{error} A has shape {a_shape} | B has shape {b_shape}\n{silly}"
        print(cust_eror)
        raise Dimension_Error(cust_eror)
    
    # Subtract and print results
    c = a - b 
    print(f'C = {c}')
    print('Done :)\n\n')
    return c
          

def multiply_two_matrices(a, b):
    """
        Use to multiply two matrices that share the same outer and inner dim together.
        Returns C, the product of the two matrices 

        a,b : Matrices/Tensors to be multiplied together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Multiplication\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A x B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape[-1] != b.shape[0]:
        a_shape = colored(a.shape[1], 'red', attrs=['bold', 'underline'] )
        b_shape = colored(b.shape[0], 'red', attrs=['bold', 'underline'] )
        error = colored('Error:', 'red', attrs=['blink'])
        silly = colored('You trying to break me?', 'blue')
        cust_eror = f"{error} (m x {a_shape}) * ({b_shape} x n).. Not compatible\n{silly}"
        print(cust_eror)
        raise Dimension_Error(cust_eror)
    
    # Dot product and print results
    c = np.dot(a, b) 
    print(f'C = {c}')
    print(f'C has shape {c.shape[0]} x {c.shape[1]}')
    print('Done :)\n\n')
    return c

# $$\Large Addition\ of\ Matrices/Tensors\\ $$

$$ \Large A_{m \times n} + B_{m \times n}  =\\ 
\large \begin{matrix}
 a_{11} & a_{12}    & \ldots &  a_{1n}\\
 a_{21}  &   a_{22} & \ldots &  a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 a_{m1}  &    a_{m2}       &\ldots &  a_{mn}
\end{matrix} + \begin{matrix}
 b_{11} & b_{12}    & \ldots &  b_{1n}\\
 b_{21}  &   b_{22} & \ldots &  b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 b_{m1}  &    b_{m2}       &\ldots &  b_{mn}
\end{matrix} = 
\begin{matrix}
 c_{11} & c_{12}    & \ldots &  c_{1n}\\
 c_{21}  &   c_{22} & \ldots &  c_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 c_{m1}  &    c_{m2}       &\ldots &  c_{mn} \end{matrix}  \\
$$

$$
    \Large Where\ A\ and \ B\ are\ both\ m \times n \ matrices
$$

In [2]:
# Two matrices with matching dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (2,3))
c = add_two_matrices(a, b)

Matrix Addition
A = [[16 18  8]
 [12 16 19]]

B = [[17  8 14]
 [ 2  9 13]]

A + B = C
A's size = (2, 3)
B's size = (2, 3)

C = [[33 26 22]
 [14 25 32]]
Done :)




## Two Matrices with mismatch dimensions... an invalid operation

In [3]:
# Two matrices with mismatch dimension
c = np.random.randint(0, 20, (2,3))
d = np.random.randint(0, 20, (5,2))
add_two_matrices(c, d)

Matrix Addition
A = [[ 2  2  1]
 [ 7 19  3]]

B = [[11 13]
 [18  0]
 [16  1]
 [19  1]
 [11 19]]

A + B = C
A's size = (2, 3)
B's size = (5, 2)

Error A has shape (2, 3) | B has shape (5, 2)
You trying to break me?


Dimension_Error: Error A has shape (2, 3) | B has shape (5, 2)
You trying to break me?

# $$\Large Subtraction\ of\ Matrices/Tensors\\ $$

$$ \Large A_{m \times n} - B_{m \times n}  =\\ 
\large \begin{matrix}
 a_{11} & a_{12}    & \ldots &  a_{1n}\\
 a_{21}  &   a_{22} & \ldots &  a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 a_{m1}  &    a_{m2}       &\ldots &  a_{mn}
\end{matrix} - \begin{matrix}
 b_{11} & b_{12}    & \ldots &  b_{1n}\\
 b_{21}  &   b_{22} & \ldots &  b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 b_{m1}  &    b_{m2}       &\ldots &  b_{mn}
\end{matrix} = 
\begin{matrix}
 c_{11} & c_{12}    & \ldots &  c_{1n}\\
 c_{21}  &   c_{22} & \ldots &  c_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 c_{m1}  &    c_{m2}       &\ldots &  c_{mn} \end{matrix}  \\
$$

$$
    \Large Where\ A\ and \ B\ are\ both\ m \times n \ matrices
$$

In [4]:
# Two matrices with matching dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (2,3))
c = subtract_two_matrices(a, b)

Matrix Subtraction
A = [[ 8 15  3]
 [ 7 12 18]]

B = [[ 6  8 12]
 [ 5  7 19]]

A + B = C
A's size = (2, 3)
B's size = (2, 3)

C = [[ 2  7 -9]
 [ 2  5 -1]]
Done :)




## Two Matrices with mismatch dimensions... an invalid operation

In [5]:
# Two matrices with mismatch dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (8,2))
c = subtract_two_matrices(a, b)

Matrix Subtraction
A = [[ 0 17  4]
 [ 5 12  2]]

B = [[ 0 16]
 [19 17]
 [ 4 10]
 [11 12]
 [15 13]
 [ 8  7]
 [ 6 11]
 [ 5 10]]

A + B = C
A's size = (2, 3)
B's size = (8, 2)

Error A has shape (2, 3) | B has shape (8, 2)
You trying to break me?


Dimension_Error: Error A has shape (2, 3) | B has shape (8, 2)
You trying to break me?

# $$\Large Multiplication\ of\ Matrices/Tensors\\ $$

$$ \Large A_{m \times r} \cdot B_{r \times n}  = \\
\large \begin{matrix}
 a_{11} & a_{12}    & \ldots &  a_{1r}\\
 a_{21}  &   a_{22} & \ldots &  a_{2r}\\
\vdots & \vdots & \ddots & \vdots\\
 a_{m1}  &    a_{m2}       &\ldots &  a_{mr}
\end{matrix} \ * \ \begin{matrix}
 b_{11} & b_{12}    & \ldots &  b_{1n}\\
 b_{21}  &   b_{22} & \ldots &  b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 b_{r1}  &    b_{r2}       &\ldots &  b_{rn}
\end{matrix} = 
\begin{matrix}
 c_{11} & c_{12}    & \ldots &  c_{1r}\\
 c_{21}  &   c_{22} & \ldots &  c_{2r}\\
\vdots & \vdots & \ddots & \vdots\\
 c_{r1}  &    c_{r2}       &\ldots &  c_{rr}
\end{matrix} \\
$$

$$
    \Large Where\ A_r\ = \ B_r\ and\ C\ is\ r\times r \ matrix
$$

In [6]:
# Two matrices with proper dimensions
a = np.random.randint(0, 20, (7,3))
b = np.random.randint(0, 20, (3,20))
c = multiply_two_matrices(a, b)

Matrix Multiplication
A = [[ 6 19 10]
 [13 12 14]
 [ 0  5  3]
 [18 17 15]
 [13  7  5]
 [ 2 13 19]
 [12  1 18]]

B = [[ 2  2  0  4 18  4 12  8  6 13 12 12 11  5 13 15 16 18  3  0]
 [14  4 19  8 10 18  7 12  4 19  2 11 11 12 18 16  4 16  0  8]
 [19 19  8 16  9 16 13  1  9  2  1  6 14  4  3 14 12 17 14 10]]

A x B = C
A's size = (7, 3)
B's size = (3, 20)

C = [[468 278 441 336 388 526 335 286 202 459 120 341 415 298 450 534 292 582
  158 252]
 [460 340 340 372 480 492 422 262 252 425 194 372 471 265 427 583 424 664
  235 236]
 [127  77 119  88  77 138  74  63  47 101  13  73  97  72  99 122  56 131
   42  70]
 [559 389 443 448 629 618 530 363 311 587 265 493 595 354 585 752 536 851
  264 286]
 [219 149 173 188 349 258 270 193 151 312 175 263 290 169 310 377 296 431
  109 106]
 [547 417 399 416 337 546 362 191 235 311  69 281 431 242 317 504 312 567
  272 294]
 [380 370 163 344 388 354 385 126 238 211 164 263 395 144 228 448 412 538
  288 188]]
C has shape 7 x 20
Done :)




## Two Matrices with mismatch dimensions... an invalid operation

In [7]:
# Two matrices with improper dimensions
a = np.random.randint(0, 20, (7,7))
b = np.random.randint(0, 20, (3,20))
c = multiply_two_matrices(a, b)

Matrix Multiplication
A = [[ 8  4 11  2 19 10 14]
 [ 4 17  7  1  3  5  7]
 [ 9  7 14  0  4 14 16]
 [ 8  7  3 10  2  7  5]
 [ 7  4  0 19 17 11  1]
 [ 4  8  8  6  4  5 16]
 [12  7 15 19  5 16  1]]

B = [[13  2  4  3 12  4 13 19 16 14  5 19 16 19 16 17 12  2 16  7]
 [10  3 15 16 19  6 13 18 10 15  0  2 14 15  3 19 11  2 19 15]
 [ 8 12  3  4  7 19 16 18 14 18 16  4 16 12 11 11 19  0 10  1]]

A x B = C
A's size = (7, 7)
B's size = (3, 20)

Error: (m x 7) * (3 x n).. Not compatible
You trying to break me?


Dimension_Error: Error: (m x 7) * (3 x n).. Not compatible
You trying to break me?

# $$\large Scalar\ Multiple \ of\ a \ Matrix/Tensor \\
5A = \begin{matrix}
5a_{11} & 5a_{12}    & \ldots & 5a_{1n}\\
5a_{21}  &  5a_{22} & \ldots & 5a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
5a_{m1}  &   5a_{m2}       &\ldots & 5a_{mn}
\end{matrix} \\ $$


In [8]:
a = np.random.randint(0,10, (2,6))
print(f'Matrix a before scaled\n{"="*48}\n{a}\n')
print(f'Matrix a Scaled by 5\n{"="*48}\n{5 * a}')

Matrix a before scaled
[[4 6 5 2 6 1]
 [0 1 1 4 9 7]]

Matrix a Scaled by 5
[[20 30 25 10 30  5]
 [ 0  5  5 20 45 35]]


# $$ \Large Transpose\ of\ a\ Matrix $$
$$ \Large Simply\ put\ A^\mathsf{T}_{ij} = A_{ji}   $$

<center> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Matrix_transpose.gif/200px-Matrix_transpose.gif">

In [9]:
a = np.random.randint(0, 20, (3,2, 2))
print(f'Before transpose: \n{"=" * 48}\n {a}')
a = np.transpose(a);
print()
print(f'After transpose: \n{"=" * 48}\n {a}')

Before transpose: 
 [[[ 8  4]
  [ 9  3]]

 [[ 0  4]
  [ 0 12]]

 [[17  1]
  [ 7 15]]]

After transpose: 
 [[[ 8  0 17]
  [ 9  0  7]]

 [[ 4  4  1]
  [ 3 12 15]]]


# Gauss-Jordan method

In [10]:
from numpy.linalg import solve

linCombo = np.eye(5)
answer = np.random.rand(5)

print(f'Linear combo:\n {linCombo} *x =  {answer}')
solution = solve(linCombo, np.transpose(answer))
print(f'\nWhere x = {solution.reshape(-1,1) }')
print()


linCombo = np.array([[0,0,1,0], [2,4,1,2], [9,3,1,.8], [22, .128, 4, 9]])
answer = np.array([0, 2, 30, 8])

print(f'Linear combo:\n {linCombo} *x =  {answer}')
solution = solve(linCombo, np.transpose(answer))
print(f'\nWhere x = {solution.reshape(-1,1) }')
print()

Linear combo:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] *x =  [0.13481298 0.89452518 0.77710907 0.13788967 0.3715554 ]

Where x = [[0.13481298]
 [0.89452518]
 [0.77710907]
 [0.13788967]
 [0.3715554 ]]

Linear combo:
 [[ 0.     0.     1.     0.   ]
 [ 2.     4.     1.     2.   ]
 [ 9.     3.     1.     0.8  ]
 [22.     0.128  4.     9.   ]] *x =  [ 0  2 30  8]

Where x = [[ 3.15909643]
 [ 2.35386378]
 [-0.        ]
 [-6.866824  ]]



# Inverse of a Matrix

In [11]:
a = np.random.randint(0, 22,(2, 4))
print(f'Before Inverse Operation: \n{"=" * 48}\n {a}')
a = np.invert(a)
print()
print(f'After Inverse Operation: \n{"=" * 48}\n {a}')

Before Inverse Operation: 
 [[19 11 15  3]
 [21  2 11  1]]

After Inverse Operation: 
 [[-20 -12 -16  -4]
 [-22  -3 -12  -2]]


# Rank of a Matrix/Tensor

In [12]:
from numpy.linalg import matrix_rank

# A 4x4 identity array
i = np.eye(4)
print(f'{i}\n Rank: {matrix_rank(i)}')
print()

# Same array but with zeros in the last row
i[-1][:] = np.zeros((1,i.shape[1]))
print(f'{i}\n Rank: {matrix_rank(i)}')


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 Rank: 4

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
 Rank: 3


# Determinates of Matrices/Tensors

In [13]:
from numpy.linalg import det

a = np.random.randint(1, 10, (2, 2))
print(f'{a}\n Determinate: {det(a):.2f}')
print()

norm = np.random.randint(0,14,(5,5))
print(f'{norm}\n Determinate: \n{det(norm):.2f}\n')
print()

[[9 9]
 [7 7]]
 Determinate: 0.00

[[ 9 12  7  0  3]
 [ 6 13 13  9 12]
 [12  8  1  2  8]
 [ 8 12 11  9  1]
 [ 8  1  2  7 10]]
 Determinate: 
-39424.00


