In [136]:
from termcolor import colored
import numpy as np

# Custom error to pass message to
class Dimension_Error(Exception):
    pass

def add_two_matrices(a, b):
    """
        Use to add two matrices that share the same dimensions together.
        Returns C, the sum of the two matrices 

        a,b : Matrices/Tensors to be added together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Addition\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A + B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape != b.shape:
        a_shape = colored(a.shape, 'red', 'on_white', attrs=['bold'] )
        b_shape = colored(b.shape, 'red', 'on_white', attrs=['bold'] )
        error = colored('Error', 'red', attrs=['blink'])
        silly = colored('You trying to break me?', 'blue')
        cust_eror = f"{error} A has shape {a_shape} | B has shape {b_shape}\n{silly}"
        print(cust_eror)
        raise Dimension_Error(cust_eror)
    
    # Add and print results
    c = a + b 
    print(f'C = {c}')
    print('Done :)\n\n')
    return c
          
def subtract_two_matrices(a, b):
    """
        Use to add two matrices that share the same dimensions together.
        Returns C, the difference of the two matrices 

        a,b : Matrices/Tensors to be subtracted together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Subtraction\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A + B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape != b.shape:
        a_shape = colored(a.shape, 'red', 'on_white', attrs=['bold'] )
        b_shape = colored(b.shape, 'red', 'on_white', attrs=['bold'] )
        error = colored('Error', 'red', attrs=['blink'])
        silly = colored('You trying to break me?', 'blue')
        cust_eror = f"{error} A has shape {a_shape} | B has shape {b_shape}\n{silly}"
        print(cust_eror)
        raise Dimension_Error(cust_eror)
    
    # Subtract and print results
    c = a - b 
    print(f'C = {c}')
    print('Done :)\n\n')
    return c
          

def multiply_two_matrices(a, b):
    """
        Use to multiply two matrices that share the same outer and inner dim together.
        Returns C, the product of the two matrices 

        a,b : Matrices/Tensors to be multiplied together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Multiplication\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A x B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape[-1] != b.shape[0]:
        a_shape = colored(a.shape[1], 'red', attrs=['bold', 'underline'] )
        b_shape = colored(b.shape[0], 'red', attrs=['bold', 'underline'] )
        error = colored('Error:', 'red', attrs=['blink'])
        silly = colored('You trying to break me?', 'blue')
        cust_eror = f"{error} (m x {a_shape}) * ({b_shape} x n).. Not compatible\n{silly}"
        print(cust_eror)
        raise Dimension_Error(cust_eror)
    
    # Dot product and print results
    c = np.dot(a, b) 
    print(f'C = {c}')
    print(f'C has shape {c.shape[0]} x {c.shape[1]}')
    print('Done :)\n\n')
    return c

# $$\Large Addition\ of\ Matrices/Tensors\\ $$

$$ \Large A_{m \times n} + B_{m \times n}  =\\ 
\large \begin{matrix}
 a_{11} & a_{12}    & \ldots &  a_{1n}\\
 a_{21}  &   a_{22} & \ldots &  a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 a_{m1}  &    a_{m2}       &\ldots &  a_{mn}
\end{matrix} + \begin{matrix}
 b_{11} & b_{12}    & \ldots &  b_{1n}\\
 b_{21}  &   b_{22} & \ldots &  b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 b_{m1}  &    b_{m2}       &\ldots &  b_{mn}
\end{matrix} = 
\begin{matrix}
 c_{11} & c_{12}    & \ldots &  c_{1n}\\
 c_{21}  &   c_{22} & \ldots &  c_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 c_{m1}  &    c_{m2}       &\ldots &  c_{mn} \end{matrix}  \\
$$

$$
    \Large Where\ A\ and \ B\ are\ both\ m \times n \ matrices
$$

In [42]:
# Two matrices with matching dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (2,3))
c = add_two_matrices(a, b)

Matrix Addition
A = [[15  5  2]
 [ 2 15  1]]

B = [[14  5  1]
 [ 5  7 13]]

A + B = C
A's size = (2, 3)
B's size = (2, 3)

C = [[29 10  3]
 [ 7 22 14]]
Done :)




## Two Matrices with mismatch dimensions... an invalid operation

In [37]:
# Two matrices with mismatch dimension
c = np.random.randint(0, 20, (2,3))
d = np.random.randint(0, 20, (5,2))
add_two_matrices(c, d)

Matrix Addition
A = [[13 19 13]
 [14 18 18]]

B = [[17  2]
 [ 5  7]
 [ 3 19]
 [16 17]
 [17 12]]

A + B = C
A's size = (2, 3)
B's size = (5, 2)

Error A has shape (2, 3) | B has shape (5, 2)
You trying to break me?


Dimension_Error: Error A has shape (2, 3) | B has shape (5, 2)
You trying to break me?

# $$\Large Subtraction\ of\ Matrices/Tensors\\ $$

$$ \Large A_{m \times n} - B_{m \times n}  =\\ 
\large \begin{matrix}
 a_{11} & a_{12}    & \ldots &  a_{1n}\\
 a_{21}  &   a_{22} & \ldots &  a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 a_{m1}  &    a_{m2}       &\ldots &  a_{mn}
\end{matrix} - \begin{matrix}
 b_{11} & b_{12}    & \ldots &  b_{1n}\\
 b_{21}  &   b_{22} & \ldots &  b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 b_{m1}  &    b_{m2}       &\ldots &  b_{mn}
\end{matrix} = 
\begin{matrix}
 c_{11} & c_{12}    & \ldots &  c_{1n}\\
 c_{21}  &   c_{22} & \ldots &  c_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 c_{m1}  &    c_{m2}       &\ldots &  c_{mn} \end{matrix}  \\
$$

$$
    \Large Where\ A\ and \ B\ are\ both\ m \times n \ matrices
$$

In [43]:
# Two matrices with matching dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (2,3))
c = subtract_two_matrices(a, b)

Matrix Subtraction
A = [[ 1  1  9]
 [19 15 14]]

B = [[18 10 14]
 [ 7  5 13]]

A + B = C
A's size = (2, 3)
B's size = (2, 3)

C = [[-17  -9  -5]
 [ 12  10   1]]
Done :)




## Two Matrices with mismatch dimensions... an invalid operation

In [44]:
# Two matrices with mismatch dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (8,2))
c = subtract_two_matrices(a, b)

Matrix Subtraction
A = [[19  4 11]
 [ 9  7 11]]

B = [[ 1  1]
 [11  9]
 [ 1  8]
 [17 12]
 [11 16]
 [13  4]
 [14  5]
 [14 10]]

A + B = C
A's size = (2, 3)
B's size = (8, 2)

Error A has shape (2, 3) | B has shape (8, 2)
You trying to break me?


Dimension_Error: Error A has shape (2, 3) | B has shape (8, 2)
You trying to break me?

# $$\Large Multiplication\ of\ Matrices/Tensors\\ $$

$$ \Large A_{m \times r} \cdot B_{r \times n}  = \\
\large \begin{matrix}
 a_{11} & a_{12}    & \ldots &  a_{1r}\\
 a_{21}  &   a_{22} & \ldots &  a_{2r}\\
\vdots & \vdots & \ddots & \vdots\\
 a_{m1}  &    a_{m2}       &\ldots &  a_{mr}
\end{matrix} \ * \ \begin{matrix}
 b_{11} & b_{12}    & \ldots &  b_{1n}\\
 b_{21}  &   b_{22} & \ldots &  b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
 b_{r1}  &    b_{r2}       &\ldots &  b_{rn}
\end{matrix} = 
\begin{matrix}
 c_{11} & c_{12}    & \ldots &  c_{1r}\\
 c_{21}  &   c_{22} & \ldots &  c_{2r}\\
\vdots & \vdots & \ddots & \vdots\\
 c_{r1}  &    c_{r2}       &\ldots &  c_{rr}
\end{matrix} \\
$$

$$
    \Large Where\ A_r\ = \ B_r\ and\ C\ is\ r\times r \ matrix
$$

In [46]:
# Two matrices with proper dimensions
a = np.random.randint(0, 20, (7,3))
b = np.random.randint(0, 20, (3,20))
c = multiply_two_matrices(a, b)

Matrix Multiplication
A = [[ 9 17 13]
 [19  2 13]
 [ 4 11 16]
 [ 0 12  6]
 [ 2 15  5]
 [13  0  2]
 [ 4  7 19]]

B = [[15 12  9  5 17 15 12 19  3  5 11 18 14  6 18 16  0  3 16 12]
 [14 17  3 15  1 18  2  2 16  1  5  6 11  4  2  7  3 12 13  9]
 [16  3 10 14  9  1  2  4  6 11 18  5  5 16  3 14 17  2  5  2]]

A x B = C
A's size = (7, 3)
B's size = (3, 20)

C = [[581 436 262 482 287 454 168 257 377 205 418 329 378 330 235 445 272 257
  430 287]
 [521 301 307 307 442 334 258 417 167 240 453 419 353 330 385 500 227 107
  395 272]
 [470 283 229 409 223 274 102 162 284 207 387 218 257 324 142 365 305 176
  287 179]
 [264 222  96 264  66 222  36  48 228  78 168 102 162 144  42 168 138 156
  186 120]
 [320 294 113 305  94 305  64  88 276  80 187 151 218 152  81 207 130 196
  252 169]
 [227 162 137  93 239 197 160 255  51  87 179 244 192 110 240 236  34  43
  218 160]
 [462 224 247 391 246 205 100 166 238 236 421 209 228 356 143 379 344 134
  250 149]]
C has shape 7 x 20
Done :)




## Two Matrices with mismatch dimensions... an invalid operation

In [53]:
# Two matrices with improper dimensions
a = np.random.randint(0, 20, (7,7))
b = np.random.randint(0, 20, (3,20))
c = multiply_two_matrices(a, b)

Matrix Multiplication
A = [[13  3  8  1 15 11 12]
 [ 4  1  5 14  5  3 14]
 [ 1 10 12 13  3  7  6]
 [ 0  8  5 10  2  3  1]
 [ 7  3  0  2 16 16 15]
 [12 15  9  7  9  4 11]
 [ 7  0  0 19  9 15 12]]

B = [[ 2  2  9 13 10  1 15 11 14  7  5  8  4 16 18 17 17 18 13  3]
 [17  7  7 17 14  2 19  5  9 11  2 16  8  1 15  3 15 12  4  6]
 [16 12  6  0 15 14 14  1 15  5 11  6  5  9  9  7  1  6  2  4]]

A x B = C
A's size = (7, 7)
B's size = (3, 20)

Error: (m x 7) * (3 x n).. Not compatible
You trying to break me?


Dimension_Error: Error: (m x 7) * (3 x n).. Not compatible
You trying to break me?

# $$\large Scalar\ Multiple \ of\ a \ Matrix/Tensor \\
5A = \begin{matrix}
5a_{11} & 5a_{12}    & \ldots & 5a_{1n}\\
5a_{21}  &  5a_{22} & \ldots & 5a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
5a_{m1}  &   5a_{m2}       &\ldots & 5a_{mn}
\end{matrix} \\ $$


In [134]:
a = np.random.randint(0,10, (2,6))
print(f'Matrix a before scaled\n{"="*48}\n{a}\n')
print(f'Matrix a Scaled by 5\n{"="*48}\n{5 * a}')

Matrix a before scaled
[[0 3 3 7 9 5]
 [6 2 8 1 8 8]]

Matrix a Scaled by 5
[[ 0 15 15 35 45 25]
 [30 10 40  5 40 40]]


# $$ \Large Transpose\ of\ a\ Matrix $$
$$ \Large Simply\ put\ \sum_{i,j = 0}^N A^\mathsf{T}_{ij} = A_{ji}   $$

<center> <img src="trans.gif">

In [11]:
a = np.random.randint(0, 20, (3,2, 2))
print(f'Before transpose: \n{"=" * 48}\n {a}')
a = np.transpose(a);
print()
print(f'After transpose: \n{"=" * 48}\n {a}')

Before transpose: 
 [[[ 6  5]
  [18  8]]

 [[ 5 17]
  [16  6]]

 [[10  8]
  [16 16]]]

After transpose: 
 [[[ 6  5 10]
  [18 16 16]]

 [[ 5 17  8]
  [ 8  6 16]]]


# Gauss-Jordan method

In [77]:
from numpy.linalg import solve

linCombo = np.eye(5)
answer = np.random.rand(5)

print(f'Linear combo:\n {linCombo} *x =  {answer}')
solution = solve(linCombo, np.transpose(answer))
print(f'\nWhere x = {solution.reshape(-1,1) }')
print()


linCombo = np.array([[0,0,1,0], [2,4,1,2], [9,3,1,.8], [22, .128, 4, 9]])
answer = np.array([0, 2, 30, 8])

print(f'Linear combo:\n {linCombo} *x =  {answer}')
solution = solve(linCombo, np.transpose(answer))
print(f'\nWhere x = {solution.reshape(-1,1) }')
print()

Linear combo:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] *x =  [0.5099534  0.40156309 0.52245251 0.94059202 0.04690028]

Where x = [[0.5099534 ]
 [0.40156309]
 [0.52245251]
 [0.94059202]
 [0.04690028]]

Linear combo:
 [[ 0.     0.     1.     0.   ]
 [ 2.     4.     1.     2.   ]
 [ 9.     3.     1.     0.8  ]
 [22.     0.128  4.     9.   ]] *x =  [ 0  2 30  8]

Where x = [[ 3.15909643]
 [ 2.35386378]
 [-0.        ]
 [-6.866824  ]]



# Inverse of a Matrix

In [12]:
a = np.random.randint(0, 22,(2, 4))
print(f'Before Inverse Operation: \n{"=" * 48}\n {a}')
a = np.invert(a)
print()
print(f'After Inverse Operation: \n{"=" * 48}\n {a}')

Before Inverse Operation: 
 [[18 14 11 14]
 [10  6 18  4]]

After Inverse Operation: 
 [[-19 -15 -12 -15]
 [-11  -7 -19  -5]]


# Rank of a Matrix/Tensor

In [115]:
from numpy.linalg import matrix_rank

# A 4x4 identity array
i = np.eye(4)
print(f'{i}\n Rank: {matrix_rank(i)}')
print()

# Same array but with zeros in the last row
i[-1][:] = np.zeros((1,i.shape[1]))
print(f'{i}\n Rank: {matrix_rank(i)}')


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 Rank: 4

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
 Rank: 3


# Determinates of Matrices/Tensors

In [123]:
from numpy.linalg import det

a = np.random.randint(1, 10, (2, 2))
print(f'{a}\n Determinate: {det(a):.2f}')
print()

norm = np.random.randint(0,14,(5,5))
print(f'{norm}\n Determinate: \n{det(norm):.2f}\n')
print()

[[3 4]
 [2 2]]
 Determinate: -2.00

[[ 0 10  5 11  3]
 [ 9  2  3  1 13]
 [ 7 11 13  5 10]
 [13  1  1 13 11]
 [ 1  2  0  6  5]]
 Determinate: 
-26394.00


