In [1]:
import numpy as np

In [ ]:
"""
Function List:
Add
Subtract
Multiply
Scale
Transpose
Gauss-Jordan Method
Inverse
Rank
Determinates
"""

## Addition and Subtraction of Matrices & Tensors

In [12]:
class Dimension_Error(Exception):
    pass
def add_two_matrices(a, b):
    """
        Use to add two matrices that share the same dimensions together.
        Returns C, the sum of the two matrices 

        a,b : Matrices/Tensors to be added together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Addition\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A + B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape != b.shape:
        raise Dimension_Error("Your dimension's do not match! You can not do this!")
    
    # Add and print results
    c = a + b 
    print(f'C = {c}')
    print('Done :)\n\n')
    return c
          
def subtract_two_matrices(a, b):
    """
        Use to add two matrices that share the same dimensions together.
        Returns C, the sum of the two matrices 

        a,b : Matrices/Tensors to be added together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Subtraction\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A + B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape != b.shape:
        raise Dimension_Error("Your dimension's do not match! You can not do this!")
    
    # Subtract and print results
    c = a - b 
    print(f'C = {c}')
    print('Done :)\n\n')
    return c
          

In [13]:
# Two matrices with matching dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (2,3))
add_two_matrices(a, b)

Matrix Addition
A = [[ 2  8 11]
 [ 2  6  4]]

B = [[ 0  1  1]
 [13  5  5]]

A + B = C
A's size = (2, 3)
B's size = (2, 3)

C = [[ 2  9 12]
 [15 11  9]]
Done :)




array([[ 2,  9, 12],
       [15, 11,  9]])

In [14]:
# Two matrices with mismatch dimension
c = np.random.randint(0, 20, (2,3))
d = np.random.randint(0, 20, (5,2))
add_two_matrices(c, d)

Matrix Addition
A = [[ 7  9  0]
 [19  1  5]]

B = [[ 7  4]
 [ 5 16]
 [ 8  0]
 [10  6]
 [ 1  0]]

A + B = C
A's size = (2, 3)
B's size = (5, 2)



Dimension_Error: Your dimension's do not match! You can not do this!

In [15]:
# Two matrices with matching dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (2,3))
subtract_two_matrices(a, b)

Matrix Subtraction
A = [[ 6  0  2]
 [14 11  7]]

B = [[10  0 10]
 [ 9  5  3]]

A + B = C
A's size = (2, 3)
B's size = (2, 3)

C = [[-4  0 -8]
 [ 5  6  4]]
Done :)




array([[-4,  0, -8],
       [ 5,  6,  4]])

In [16]:
# Two matrices with mismatch dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (8,2))
subtract_two_matrices(a, b)

Matrix Subtraction
A = [[16 18 16]
 [ 1  6  1]]

B = [[15 12]
 [16  2]
 [ 8 13]
 [ 1  0]
 [16  9]
 [14 10]
 [17 12]
 [15  8]]

A + B = C
A's size = (2, 3)
B's size = (8, 2)



Dimension_Error: Your dimension's do not match! You can not do this!