In [1]:
import numpy as np

In [3]:
class Dimension_Error(Exception):
    pass
def add_two_matrices(a, b):
    """
        Use to add two matrices that share the same dimensions together.
        Returns C, the sum of the two matrices 

        a,b : Matrices/Tensors to be added together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Addition\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A + B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape != b.shape:
        raise Dimension_Error("Your dimension's do not match! You can not do this!")
    
    # Add and print results
    c = a + b 
    print(f'C = {c}')
    print('Done :)\n\n')
    return c
          
def subtract_two_matrices(a, b):
    """
        Use to add two matrices that share the same dimensions together.
        Returns C, the difference of the two matrices 

        a,b : Matrices/Tensors to be subtracted together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Subtraction\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A + B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape != b.shape:
        raise Dimension_Error("Your dimension's do not match! You can not do this!")
    
    # Subtract and print results
    c = a - b 
    print(f'C = {c}')
    print('Done :)\n\n')
    return c
          

# Addition of Matrices & Tensors

In [4]:
# Two matrices with matching dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (2,3))
add_two_matrices(a, b)

Matrix Addition
A = [[13 16 16]
 [ 9 14 15]]

B = [[12  5 10]
 [ 8  4  4]]

A + B = C
A's size = (2, 3)
B's size = (2, 3)

C = [[25 21 26]
 [17 18 19]]
Done :)




array([[25, 21, 26],
       [17, 18, 19]])

## Two Matrices with mismatch dimensions... an invalid operation

In [5]:
# Two matrices with mismatch dimension
c = np.random.randint(0, 20, (2,3))
d = np.random.randint(0, 20, (5,2))
add_two_matrices(c, d)

Matrix Addition
A = [[ 8  3  7]
 [10 12 10]]

B = [[ 7 11]
 [ 1 16]
 [ 0 14]
 [ 8 19]
 [19  2]]

A + B = C
A's size = (2, 3)
B's size = (5, 2)



Dimension_Error: Your dimension's do not match! You can not do this!

# Subtraction of Matrices & Tensors

In [6]:
# Two matrices with matching dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (2,3))
c = subtract_two_matrices(a, b)

Matrix Subtraction
A = [[10  5  3]
 [19  1 17]]

B = [[11  1 17]
 [12  5  5]]

A + B = C
A's size = (2, 3)
B's size = (2, 3)

C = [[ -1   4 -14]
 [  7  -4  12]]
Done :)




## Two Matrices with mismatch dimensions... an invalid operation

In [7]:
# Two matrices with mismatch dimensions
a = np.random.randint(0, 20, (2,3))
b = np.random.randint(0, 20, (8,2))
c = subtract_two_matrices(a, b)

Matrix Subtraction
A = [[ 5  8 18]
 [ 2 16  5]]

B = [[15 16]
 [ 1 12]
 [11  7]
 [14 14]
 [ 3 10]
 [14  7]
 [ 2 12]
 [13  5]]

A + B = C
A's size = (2, 3)
B's size = (8, 2)



Dimension_Error: Your dimension's do not match! You can not do this!

# Matrix multiplication

In [8]:
def multiply_two_matrices(a, b):
    """
        Use to multiply two matrices that share the same outer and inner dim together.
        Returns C, the product of the two matrices 

        a,b : Matrices/Tensors to be multiplied together
    """
    
    # Output for User's Sanity 
    print(f'Matrix Multiplication\n{"=" * 30}')
    print(f'A = {a}\n')
    print(f'B = {b}\n')
    print('A x B = C')
    print(f'A\'s size = {a.shape}')      
    print(f'B\'s size = {b.shape}')      
    print()

    # Check dimensions and raise a user friendly error, if nessecary
    if a.shape[-1] != b.shape[0]:
        print(f'm x {a.shape[1]} and  {b.shape[0]} x n are not incompatible')
        raise Dimension_Error("Your dimension's do not match! You can not do this!")
    
    # Dot product and print results
    c = np.dot(a, b) 
    print(f'C = {c}')
    print(f'C has shape {c.shape[0]} x {c.shape[1]}')
    print('Done :)\n\n')
    return c
          

In [9]:
# Two matrices with proper dimensions
a = np.random.randint(0, 20, (7,3))
b = np.random.randint(0, 20, (3,20))
c = multiply_two_matrices(a, b)

Matrix Multiplication
A = [[15  4 12]
 [11 14  0]
 [ 0 14 19]
 [ 7 11 17]
 [17  5  3]
 [18 17 15]
 [ 2  5 17]]

B = [[ 6 15  2  1  0  8  3  3 15  7 13 18  8 14 12 11 17  3  0  2]
 [12  0 11  0 13 15  2  9  2  4  8 19 16  6 14 18  2  8  6  1]
 [ 9 16  9 14  2  6 19  6  5 14 17  5  5  9  0  5  1 16 11  6]]

A x B = C
A's size = (7, 3)
B's size = (3, 20)

C = [[246 417 182 183  76 252 281 153 293 289 431 406 244 342 236 297 275 269
  156 106]
 [234 165 176  11 182 298  61 159 193 133 255 464 312 238 328 373 215 145
   84  36]
 [339 304 325 266 220 324 389 240 123 322 435 361 319 255 196 347  47 416
  293 128]
 [327 377 288 245 177 323 366 222 212 331 468 420 317 317 238 360 158 381
  253 127]
 [189 303 116  59  71 229 118 114 280 181 312 416 231 295 274 292 302 139
   63  57]
 [447 510 358 228 251 489 373 297 379 404 625 722 491 489 454 579 355 430
  267 143]
 [225 302 212 240  99 193 339 153 125 272 355 216 181 211  94 197  61 318
  217 111]]
C has shape 7 x 20
Done :)




## Two Matrices with mismatch dimensions... an invalid operation

In [10]:
# Two matrices with improper dimensions
a = np.random.randint(0, 20, (7,7))
b = np.random.randint(0, 20, (3,20))
c = multiply_two_matrices(a, b)

Matrix Multiplication
A = [[12  6  3  4  0 13  7]
 [12  9 11  8  1 19 11]
 [ 2  4  0 17 12 13  3]
 [ 8 17  7 16  8 16 13]
 [ 3 12 15 19 10 12  5]
 [10  1 12 18 12 18 19]
 [11  0 17 15  1  8 18]]

B = [[16  7  2 14 11  0  5 19 11 14 18 14 18  6 13  4  6 12  4  3]
 [ 8  7 17 14  9  8  8 16 18  7 13  2 14 18  0  1 10 13 10 13]
 [ 9 10 15 17 16  3 13 14  9 14  1 19  9  1 15 11  5 13 11  9]]

A x B = C
A's size = (7, 7)
B's size = (3, 20)

m x 7 and  3 x n are not incompatible


Dimension_Error: Your dimension's do not match! You can not do this!

# Scale of a Matrix


In [53]:
s = np.random.randint(-4, 40, (3, 4))
xyz = np.array([.4, .8, .2, 1])
print(f'3 x 4 matrix: \n{"=" * 48}')
print(s)
print()
      
print(f'1 x 4 (To be tranposed to 4 x 1) : \n{"=" * 48}\n {xyz}')
s_scale = np.dot(s, xyz)
s_scale = np.transpose(s_scale)
print()
s_scale

3 x 4 matrix: 
[[-4 38  0  5]
 [15  3 29 13]
 [ 8 -1 -1 -2]]

1 x 4 (To be tranposed to 4 x 1) : 
 [0.4 0.8 0.2 1. ]



array([33.8, 27.2,  0.2])

# Transpose of a Matrix

In [11]:
a = np.random.randint(0, 20, (3,2, 2))
print(f'Before transpose: \n{"=" * 48}\n {a}')
a = np.transpose(a);
print()
print(f'After transpose: \n{"=" * 48}\n {a}')

Before transpose: 
 [[[ 6  5]
  [18  8]]

 [[ 5 17]
  [16  6]]

 [[10  8]
  [16 16]]]

After transpose: 
 [[[ 6  5 10]
  [18 16 16]]

 [[ 5 17  8]
  [ 8  6 16]]]


# Gauss-Jordan method

In [77]:
from numpy.linalg import solve

linCombo = np.eye(5)
answer = np.random.rand(5)

print(f'Linear combo:\n {linCombo} *x =  {answer}')
solution = solve(linCombo, np.transpose(answer))
print(f'{solution}')
print()


linCombo = np.array([[0,0,1,0], [2,4,1,2], [9,3,1,.8], [22, .128, 4, 9]])
answer = np.array([0, 2, 30, 8])

print(f'Linear combo:\n {linCombo} * x = {answer}')
solution = solve(linCombo, answer)
print(f'Where x = {solution}')
print()

Linear combo:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] *x =  [0.8819444  0.10502552 0.50895461 0.13054228 0.7275116 ]
[0.8819444  0.10502552 0.50895461 0.13054228 0.7275116 ]

Linear combo:
 [[ 0.     0.     1.     0.   ]
 [ 2.     4.     1.     2.   ]
 [ 9.     3.     1.     0.8  ]
 [22.     0.128  4.     9.   ]] * x = [ 0  2 30  8]
Where x = [ 3.15909643  2.35386378 -0.         -6.866824  ]



# Inverse of a Matrix

In [12]:
a = np.random.randint(0, 22,(2, 4))
print(f'Before Inverse Operation: \n{"=" * 48}\n {a}')
a = np.invert(a)
print()
print(f'After Inverse Operation: \n{"=" * 48}\n {a}')

Before Inverse Operation: 
 [[18 14 11 14]
 [10  6 18  4]]

After Inverse Operation: 
 [[-19 -15 -12 -15]
 [-11  -7 -19  -5]]


# Rank of a Matrix/Tensor

In [15]:
from numpy.linalg import matrix_rank

i = np.eye(4)
print(f'{i}\n Rank: {matrix_rank(i)}')
print()

x = np.random.rand(2, 5, 2)
print(f'{x}\n Rank: {matrix_rank(x)}')


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 Rank: 4

[[[9.26641966e-01 1.40617492e-01]
  [2.76646874e-01 6.93432706e-01]
  [5.80321407e-04 8.58553128e-01]
  [9.64710237e-01 3.91288204e-01]
  [2.04610874e-01 2.78527552e-01]]

 [[4.18687307e-01 5.14562745e-01]
  [8.89500548e-01 9.12876525e-02]
  [4.94550154e-01 5.74229407e-01]
  [7.37459845e-01 3.01175176e-01]
  [1.61471014e-01 7.49510677e-02]]]
 Rank: [2 2]


# Determinates of Matrices/Tensors

In [24]:
from numpy.linalg import det

a = np.random.randint(-100, 100, (3, 3))
print(f'{a}\n Determinate: {det(a)}')
print()

norm = np.random.randn(4,2)
print(f'{norm}\n Determinate: \n{norm}\n')
print()

[[  52   52 -100]
 [ -40   90   26]
 [ -97    9  -80]]
 Determinate: -1521112.000000002

[[-1.38178508 -1.17813688]
 [ 0.89188565  1.15918085]
 [-0.87687608  0.43023999]
 [ 0.3124563  -0.89023657]]
 Determinate: 
[[-1.38178508 -1.17813688]
 [ 0.89188565  1.15918085]
 [-0.87687608  0.43023999]
 [ 0.3124563  -0.89023657]]


